Sprint 1/step 2
GrafDev/react-burger pull request #4
Opened 2023-03-12 16:54 UTC by GrafDev

corrected

2023-03-13 09:06 UTC, andryxxa93 commented
> Добавил закрытие модалки по ESC. но уже после pull request. Сделать еще один pulll?

Нет, вполне достаточно добавлять коммиты. Это нормальная практика в открытый pull-request добавлять новые коммиты 😊

2023-03-13 09:17 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect и PropTypes.

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- У булок не должно быть иконки удаления, там должн быть иконка замка - пожалуйста посмотрите как в фигме.
- Modal должен содержать в себе `ModalOverlay`, а не наоборот.
- Не нужно создавать дополнительный `div` в `ModalOverlay`
- createPortal нужно использовать внутри `Modal`. `ModalOverlay` это просто подложка.
- Добавьте `isRequired` для полей ингредиента

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-03-13 09:17 UTC, andryxxa93 commented on src/components/modal/modal-overlay.jsx
> +	});
**Необходимо исправить**
Создавать дополнительный `div` не нужно, без него вполне нормально встраивается модальное окно.

2023-03-13 09:17 UTC, andryxxa93 commented on src/utils/types.js
> +			_id: PropTypes.string,
**Надо исправить**

в описании propTypes этого и других полей нужно указывать .isRequired, без этого не контролируется, что поле передается

2023-03-13 14:47 UTC, GrafDev commented on src/utils/types.js
> +			_id: PropTypes.string,
.isRequired добавил

2023-03-14 04:21 UTC, GrafDev commented
Я все исправил, мне делать новый пул, чтобы зачлась работа в Практикуме? Или достаточно тут написать?

2023-03-14 04:32 UTC, merged